name: Test Validation Action

on:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '.github/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: run custom docker testLog
      id: testAction
      uses: ./
      with:
        run-script-python3: 'test/version.py'
    - name: Get the output result
      run: echo -e "The result is ${{ steps.testAction.outputs.resultpython3 }}"
